### ISSUE TITLE
Column compare failing with utf-16-le codec

### ISSUE THREAD

**Issue by jmorelandsbiz** [mrinalsardar/tulona#21]
I'm getting the following error which causes the Row Comparison tab to be missing in the spreadsheet:
`[2024-04-23 08:33:32,368] {compare.py:440} ERROR - Row comparison failed with error: 'utf-16-le' codec can't decode bytes in position 20-21: illegal UTF-16 surrogate`

**Comment by mrinalsardar** [comment]
@jmorelandsbiz could you please share your `tulona-project.yml` file?

**Comment by mrinalsardar** [comment]
Went through the issue and it seems to be data related. Closing this issue.
